// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A trivia answering AI agent.
 *
 * - answerTrivia - A function that handles the trivia answering process.
 * - AnswerTriviaInput - The input type for the answerTrivia function.
 * - AnswerTriviaOutput - The return type for the answerTrivia function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnswerTriviaInputSchema = z.object({
  question: z.string().describe('The trivia question about Google.'),
  answer: z.string().describe('The player provided answer to the trivia question.'),
});
export type AnswerTriviaInput = z.infer<typeof AnswerTriviaInputSchema>;

const AnswerTriviaOutputSchema = z.object({
  isCorrect: z.boolean().describe('Whether the answer is correct or not.'),
  explanation: z.string().describe('The explanation of why the answer is correct or incorrect.'),
});
export type AnswerTriviaOutput = z.infer<typeof AnswerTriviaOutputSchema>;

export async function answerTrivia(input: AnswerTriviaInput): Promise<AnswerTriviaOutput> {
  return answerTriviaFlow(input);
}

const prompt = ai.definePrompt({
  name: 'answerTriviaPrompt',
  input: {schema: AnswerTriviaInputSchema},
  output: {schema: AnswerTriviaOutputSchema},
  prompt: `You are an expert trivia master specializing in Google history.

You will use this information to judge the answer to the question.

Question: {{{question}}}
Answer: {{{answer}}}

Make a determination as to whether the answer is correct or not, and set the isCorrect output field appropriately. Regardless of whether the answer is correct or not, provide an explanation in the explanation output field.`, safetySettings: [
    {
      category: 'HARM_CATEGORY_HATE_SPEECH',
      threshold: 'BLOCK_ONLY_HIGH',
    },
    {
      category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
      threshold: 'BLOCK_NONE',
    },
    {
      category: 'HARM_CATEGORY_HARASSMENT',
      threshold: 'BLOCK_MEDIUM_AND_ABOVE',
    },
    {
      category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
      threshold: 'BLOCK_LOW_AND_ABOVE',
    },
  ],
});

const answerTriviaFlow = ai.defineFlow(
  {
    name: 'answerTriviaFlow',
    inputSchema: AnswerTriviaInputSchema,
    outputSchema: AnswerTriviaOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
